# Generated by Django 4.2.24 on 2025-09-26 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Packet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srcip', models.GenericIPAddressField(blank=True, null=True)),
                ('sport', models.IntegerField(blank=True, null=True)),
                ('dstip', models.GenericIPAddressField(blank=True, null=True)),
                ('dsport', models.IntegerField(blank=True, null=True)),
                ('proto', models.CharField(blank=True, max_length=16, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
